
CREATE TABLE marksheet (
    student_id INT,
    name VARCHAR(50),
    subject VARCHAR(30),
    marks INT,
    grade CHAR(1)
);

INSERT INTO marksheet (student_id, name, subject, marks, grade) VALUES
(1, 'Amit Sharma', 'Math', 85, 'A'),
(2, 'Riya Gupta', 'Science', 72, 'B'),
(3, 'Vikram Singh', 'English', 90, 'A'),
(4, 'Sneha Verma', 'History', 66, 'C'),
(5, 'Arjun Mehta', 'Math', 58, 'D'),
(6, 'Pooja Rani', 'Science', 80, 'A'),
(7, 'Rohan Das', 'English', 77, 'B'),
(8, 'Kavita Nair', 'History', 69, 'C'),
(9, 'Manish Tiwari', 'Math', 91, 'A'),
(10, 'Priya Sen', 'Science', 73, 'B'),
(11, 'Deepak Yadav', 'English', 61, 'C'),
(12, 'Sonal Kaur', 'History', 82, 'B'),
(13, 'Rakesh Jain', 'Math', 55, 'D'),
(14, 'Anjali Patil', 'Science', 88, 'A'),
(15, 'Suresh Rathi', 'English', 70, 'B'),
(16, 'Neha Joshi', 'History', 92, 'A'),
(17, 'Aman Khan', 'Math', 79, 'B'),
(18, 'Divya Malhotra', 'Science', 67, 'C'),
(19, 'Rahul Mishra', 'English', 64, 'C'),
(20, 'Meena Kumari', 'History', 75, 'B'),
(21, 'Tushar Goel', 'Math', 83, 'A'),
(22, 'Priti Sahu', 'Science', 71, 'B'),
(23, 'Karan Arora', 'English', 59, 'D'),
(24, 'Nisha Dubey', 'History', 87, 'A'),
(25, 'Alok Tripathi', 'Math', 62, 'C'),
(26, 'Geeta Rathi', 'Science', 77, 'B'),
(27, 'Mohit Sinha', 'English', 68, 'C'),
(28, 'Shruti Lamba', 'History', 89, 'A'),
(29, 'Nitin Rawat', 'Math', 74, 'B'),
(30, 'Tina Desai', 'Science', 69, 'C'),
(31, 'Harsh Kapoor', 'English', 80, 'A'),
(32, 'Reena Sharma', 'History', 60, 'D'),
(33, 'Varun Bhatt', 'Math', 76, 'B'),
(34, 'Pallavi Nair', 'Science', 85, 'A'),
(35, 'Sanjay Kumar', 'English', 66, 'C'),
(36, 'Isha Saxena', 'History', 78, 'B'),
(37, 'Yuvraj Singh', 'Math', 81, 'A'),
(38, 'Ritika Rao', 'Science', 72, 'B'),
(39, 'Dinesh Babu', 'English', 63, 'C'),
(40, 'Ankita Ghosh', 'History', 91, 'A'),
(41, 'Ravi Prasad', 'Math', 70, 'B'),
(42, 'Mitali Jain', 'Science', 74, 'B'),
(43, 'Arti Vyas', 'English', 87, 'A'),
(44, 'Siddharth Yadav', 'History', 68, 'C'),
(45, 'Lakshmi Pillai', 'Math', 90, 'A'),
(46, 'Sameer Khan', 'Science', 65, 'C'),
(47, 'Bhavna Joshi', 'English', 58, 'D'),
(48, 'Naveen Rao', 'History', 79, 'B'),
(49, 'Swati Das', 'Math', 82, 'A'),
(50, 'Vivek Anand', 'Science', 60, 'D');
